echo Test
alias 0='ssh amusinglosing.corp.ne1.yahoo.com'
alias 1='ssh explainedfeigned.corp.ne1.yahoo.com'
alias 2='ssh becomefrom.corp.gq1.yahoo.com; cd Mail/storm'
alias 3='ssh oxy-oxygen-0a5a98d1.corp.gq1.yahoo.com'
alias ctci='cd /Users/rpriya/Documents/BooksToRead/prep/ques/ctci'
alias s='cd Documents/Coding/storm/'
alias test='cd ~/Documents/Coding/storm/tests/mocha-tests; make unit'
alias st='git status'
alias growth='cd=/home/rpriya/dev/workspace/'
alias ci='git commit'
alias br='git branch'
alias gp='git push'
alias odin='cd ~/yahoo/mail/odin'
alias com='git checkout master'
alias lo='git log'
alias fe='git fetch storm'
alias ck='git checkout'
alias md='cd ~/;cd storm/storm/src;make dev'
alias deleteBranch='git branch | grep -v "develop" | grep -v "master" | xargs
git branch -D'
alias update='git pull upstream master;git push origin master'
alias smoke='cd ~/Documents/Coding/storm/tests/functional'

